### DISCUSSION TITLE
Why is the textfield wrapper doubling the appearance selector?

### DISCUSSION THREAD

**Discussion by loxy** [taiga-family/taiga-ui#1192] [Q&A] [answered]
Hi!

In https://github.com/taiga-family/taiga-ui/blob/bf55bb15a56620c24fb579a7bad5a70356e4728a/projects/core/styles/theme/wrapper/textfield.less#L8 

the selector is doubled (twice `[data-appearance='textfield']`). But it should be:

```scss
tui-wrapper[data-appearance='textfield'] {
    transition: var(--tui-duration) ease-in-out;
    transition-property: box-shadow, background;
    background: var(--tui-base-01);
    color: var(--tui-text-01);
    box-shadow: 0 0.125rem 0.1875rem rgba(0, 0, 0, 0.1);

    &:after {
        transition: color var(--tui-duration) ease-in-out;
        border-width: 1px;
        color: var(--tui-base-03);
    }
...
```

Has it a special reason or is it copy & paste artefact?

Best regards,
Kersten
