### DISCUSSION TITLE
Prevent requests to `https://fonts.googleapis.com`

### DISCUSSION THREAD

**Discussion by robingenz** [taiga-family/taiga-ui#1924] [Q&A] [answered]
I am not allowed to make requests to `https://fonts.googleapis.com` for privacy reasons (GDPR). Instead I use another font, which I host on my own server:
```scss
:root {
  --tui-font-heading: "Inter var";
  --tui-font-text: "Inter var";
}

```
How can I prevent the request to `https://fonts.googleapis.com`?

https://github.com/taiga-family/taiga-ui/blob/173213fa013c73ea38e2afbc16c5ba3f3996bae3/projects/core/styles/theme/fonts.css#L1

![grafik](https://user-images.githubusercontent.com/13857929/173869217-c154af12-b686-486d-8edd-3f18cc2b2d50.png)
