### DISCUSSION TITLE
Right way to customize hint?

### DISCUSSION THREAD

**Discussion by loxy** [taiga-family/taiga-ui#2699] [Q&A] [answered]
Hi!

I know that the hint was improved. But for me it is not clear how to customize it correctly. I'm aware of #1258 

So, it is now possible to change appearance via `[tuiHintAppearance]`, but only for individual hints.

Especially, I want to know how to set the background for all hints globally. Is it already possible?

Currently we are doing something like this:

```css
tui-hint {
  --tui-primary: var(--tui-base-09) !important;
}
```

I am willing to adapt the docs accordingly!

Best regards,
Kersten
