### DISCUSSION TITLE
Code first for ltr / rtl

### DISCUSSION THREAD

**Discussion by splincode** [taiga-family/taiga-ui#6081] [Ideas]
In our code base

```less
// less
.banner {
  padding-inline: 20px 40px;
}
```

After building in bundle

```css
/* css */
.banner:dir(ltr) {
  padding-left: 20px; 
  padding-right: 40px;
}

.banner:dir(rtl) {
  padding-right: 20px; 
  padding-left: 40px;
}
```

PostCSS plugin: https://github.com/csstools/postcss-logical

What do you think about migrate to https://drafts.csswg.org/css-logical/?
