### DISCUSSION TITLE
Remove background: var(--tui-base-01); from body?

### DISCUSSION THREAD

**Discussion by sommmen** [taiga-family/taiga-ui#6899] [Q&A] [answered]
Hiya,

I'm using a single component from the taiga-ui. 
The taiga root component seems to set `background: var(--tui-base-01);` on my body.
I want it to not do that; it now overwrites other settings (and breaks my dark mode).

Is there a way to turn this off?
I'm not the best with css so it could be something basic.

**Comment by sommmen** [comment]
It seems this fixes it:

``` css
/* Remove taig-ui properties */
body[data-tui-theme] {
  font: unset !important;
  color: unset !important;
  background: unset !important;
  margin: unset !important
}
```
