### DISCUSSION TITLE
Color scheme

### DISCUSSION THREAD

**Discussion by splincode** [taiga-family/taiga-ui#9311] [Ideas]
@waterplea what do you think about add some 

```css
[tuiTheme='dark'] {
  color-scheme: dark;

   // Backgrounds
   --tui-background-base: #222;
}

&:root,
[tuiTheme='light'] {
  color-scheme: light;

  // Backgrounds
  --tui-background-base: #fff;
}
```

It's can helps have such entries in the code for custom styles in user's pet/own projects

```css
/* If user prefers a dark appearance */
@media (prefers-color-scheme: dark) {
  .my-class {
    // my styles
  }
}
```

instead of 

```css
  [tuiTheme='dark'] .my-class {
    // my styles
  }
```
