### ISSUE TITLE
🐞 - CardLarge `--t-radius` values are hardcoded for all `space` variants

### ISSUE THREAD

**Issue by dequubi** [taiga-family/taiga-ui#10038]
### Reproduction url

https://github.com/taiga-family/taiga-ui/blob/main/projects/layout/components/card/card.styles.less

### Description

```less
[tuiCardLarge][data-space] {
    /* ... */
    --t-radius: var(--tui-radius-l); // this value is not used, since `space='normal'` is default

    border-radius: var(--t-radius);
    /* ... */

    &[data-space='normal'] {
        --t-radius: 1.5rem;
        /* ... */
    }

    &[data-space='compact'] {
        --t-radius: 1rem;
        /* ... */
    }
}
```
```ts
@Directive({
    standalone: true,
    selector: '[tuiCardLarge]',
    host: {
        tuiCardLarge: '',
        '[attr.data-space]': 'space || "normal"', // <-- if empty, normal is used
    },
})
export class TuiCardLarge {
    protected readonly nothing = tuiWithStyles(TuiCardStyles);

    @Input('tuiCardLarge')
    public space: '' | 'compact' | 'normal' = 'normal';
}
```
It makes it impossible to change CardLarge `border-radius` via overriding `--tui-radius` variables globally.

Also `border-radius` of `1rem` doesn't exist across all `--tui-radius` variables, which makes design inconsistent. Is it intentional?

### Taiga UI version

4.18.0

### Browser Used

Chrome

### OS Used

Windows
