### ISSUE TITLE
🚀 - `ProgressCircle` has new sizes

### ISSUE THREAD

**Issue by nsbarsukov** [taiga-family/taiga-ui#4578]
### Description

See new design [in Figma](https://www.figma.com/file/Fi1gljzXB93tq75GyfUVQ5/Taiga-3.0?type=design&node-id=30604-179025&t=fNssaFGDDt2fpfD2-4).

It has 5 sizes.
But now `ProgressCircle` has only 4.

### Proposed solution

In **Taiga 4.0** release

1. Replace
https://github.com/Tinkoff/taiga-ui/blob/5f6b48433097b9aa41857ad7282cd714ac25dad1/projects/kit/components/progress/progress-circle/progress-circle.style.less#L4-L9
with
```less
 @width: { 
     @xs: 2em; 
     @s: 3em; 
     @m: 4em; 
     @l: 6em; 
     @xl: 8em; 
 }; 
```

2. Replace 
https://github.com/Tinkoff/taiga-ui/blob/5f6b48433097b9aa41857ad7282cd714ac25dad1/projects/kit/components/progress/progress-circle/progress-circle.component.ts#L44
with
```ts
    size: TuiSizeXL | TuiSizeXS = 'm';
```
