### ISSUE TITLE
🤖 - Add migration for proprietary colors

### ISSUE THREAD

**Issue by splincode** [taiga-family/taiga-ui#7130]
### Description

before

```less
.class {
 color: var(--tui-text-01);
 // ...
}
```

after 

```less
.class {
 color: var(--tui-text-primary);
 // ...
}
```
