### ISSUE TITLE
🐞 - Missing migration for style variable `@space`

### ISSUE THREAD

**Issue by nsbarsukov** [taiga-family/taiga-ui#8359]
### Playground Link

review-frontend

### Description

```less
@import '@taiga-ui/core/styles/taiga-ui-local.less';

:host {
    display: block;
}

.link {
    padding: @space;
}

.link + .link {
    margin-left: @space;
}

```

### Angular version

17

### Taiga UI version

4.0.0-rc.8

### Which browsers have you used?

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [ ] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android
