### ISSUE TITLE
🐞 - Missing migration for style mixin `shadow`

### ISSUE THREAD

**Issue by nsbarsukov** [taiga-family/taiga-ui#8363]
### Playground Link

review-frontend

### Description

```less
.outline-hoverable:hover {
    .shadow(4);
}

.category {
    &:hover {
        .shadow(2);
        cursor: pointer;
    }
}

:host {
    display: block;

    &._shadow {
        .shadow();
    }
}
```

### Taiga UI version

4.0.0-rc.8
