### ISSUE TITLE
🐞 - Dropdown popup shrinks when using tuiDropdownAlign

### ISSUE THREAD

**Issue by scrolltex** [taiga-family/taiga-ui#8732]
### Playground Link

https://stackblitz.com/edit/angular-qwnzfd

### Description

I created a dropdown with a select wrapped with div that has constant size in css.
When `tuiDropdownAlign` was added with any value сlicking on a select in dropdown causes popup to shrink to the width of the dropdown host.

![image](https://github.com/user-attachments/assets/68193f7d-2fe8-47e6-bfb3-c2f43bc4b3b2)
![image](https://github.com/user-attachments/assets/fd4b3cd3-c190-42a0-81ef-0bf091614dfd)

### Angular version

18.2.1

### Taiga UI version

4.4.1

### Which browsers have you used?

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Which operating systems have you used?

- [ ] macOS
- [X] Windows
- [ ] Linux
- [ ] iOS
- [ ] Android

**Comment by scrolltex** [comment]
I do my own research, i think problem in created `tui-dropdown` in portal:
At first open `tui-dropdown` creates with this styles at element:
```css
element.style {
    position: absolute;
    top: 58px;
    left: 324px;
    max-height: 400px;
}
```

After click on `tui-select` (or multi) in dropdown content, styles sets to:
```css
element.style {
    position: absolute;
    top: 58px;
    left: 503px;
    max-height: 400px;
    width: 44px;
}
```

When i add `console.log` for `limitWidth` in [TuiDropdownComponent.getStyles](https://github.com/taiga-family/taiga-ui/blob/8f6706b81021768658b2d5e1114fe892a4cc8e03/projects/core/directives/dropdown/dropdown.component.ts#L100) it print next logs:
![image](https://github.com/user-attachments/assets/a97b8f1a-f1c8-4e83-a28f-b1c2964a8fdb)

It looks like `tui-dropdown` lost initially provided options after clicking on `tui-select`.
