### ISSUE TITLE
🐞 - different behavior border radius for [data-type=holiday]

### ISSUE THREAD

**Issue by splincode** [taiga-family/taiga-ui#9222]
### Code Example URL

https://taiga-ui.dev/components/calendar

## V3

<img width="435" alt="image" src="https://github.com/user-attachments/assets/451be722-9a15-46ff-8121-8abe16bb6e09">

## V4

<img width="444" alt="image" src="https://github.com/user-attachments/assets/4e603cc1-0c6b-4231-8c16-85ccfd9183ab">

### Taiga UI version

latest

### Browser Used

Chrome

### OS Used

macOS

**Comment by waterplea** [comment]
Need to change styles in demo example from:
```css
tui-calendar-sheet [data-type='holiday'] {
    background-color: var(--tui-chart-categorical-09);
}
```
to
```css
tui-calendar-sheet [data-type='holiday']::before {
    background-color: var(--tui-chart-categorical-09);
}
```
