### ISSUE TITLE
🚀 - `tuiLabel` required asterisk indicator

### ISSUE THREAD

**Issue by FranckG28** [taiga-family/taiga-ui#9519]
### Description

When an input is required, a common UX pattern is to add a little red asterisk next to the input label. 

_example: the current input i'm using to write this_
![image](https://github.com/user-attachments/assets/a763342b-4721-415d-b333-96028f2567e0)

<details>

<summary>How I've implemented it with Taiga 3.0</summary>

With Taiga 3.x, i've added a simple css rule to add this asterisk
<img width="537" alt="image" src="https://github.com/user-attachments/assets/30b9881a-8df0-4ca4-95a4-b027e717416a">
```scss
    [tuiLabelRequired] .t-text::after {
        content: '*';
        @apply text-red-600 text-base ml-1;
    }
```

Now with Taiga 4, since the label text is not wrapped into anything, it's not possible (as far as I know) to match it :
![image](https://github.com/user-attachments/assets/e06e33de-5a49-43d8-b286-69ccf4d786be)

</details>

Since this is a very common UX pattern, I believe it could be a simple and useful feature to add.
It could be very simple to use. Example :
```html
<label tuiLabel [required]="true">
   My label
   <input />
</label>
```
