### ISSUE TITLE
🐞 - TuiFile: incorrect styles when using the `a[tuiFile]` case

### ISSUE THREAD

**Issue by algashev123** [taiga-family/taiga-ui#9630]
### Reproduction url

https://stackblitz.com/edit/angular-pxpwxg?file=src%2Fapp%2Fapp.template.html

### Description

When using `a[tuiFile]` and `[max]` input in `<tui-files>` a problem arises: if expand is drawn, the styles available for selecting the file component are not applied to the elements that are rendered via `a[tuiFile]. 

```css
tui-files .t-extra-items tui-file {
  border-radius: 0;
  margin-top: 0;
  margin-bottom: -.0625rem;
}
```

### Taiga UI version

4.12.0

### Browser Used

Chrome

### OS Used

macOS
